DL Lab Experiment 3 Excercise Questions

Create a raw dataset with more rows and columns.

Delete the column with the most missing values.

Convert the pre-processed dataset to the tensor format.

Basic Properties of Tensor Arithmetic

Reduction

**Reading the dataset**

In [ ]:
import os
os.makedirs(os.path.join('..','data'), exist_ok=True)
data_file = os.path.join('..','data', 'student_data.csv')
with open(data_file,'w') as f:
  f.write('''Name,Ambition,Fav_Sub,Concession,Certifications,Fee,CGPA
  A,Placements,DL,10000,3,90000,9.5
  B,NA,ML,10000,4,90000,9.2
  C,M.Tech,AI,NA,2,100000,7.8
  D,NA,ML,NA,NA,100000,8.9
  E,NA,DBMS,NA,NA,100000,8.2
  F,Placements,DAA,10000,4,90000,9.6
  G,NA,DS,10000,1,90000,9.0
  H,Placements,DS,10000,NA,90000,9.8
  I,MBA,DL,NA,2,100000,8.5
  J,MBA,DBMS,NA,NA,100000,7.6
  K,M.Tech,ML,10000,3,90000,9.3
  L,Placements,AI,NA,4,100000,8.7
  M,NA,DBMS,NA,1,100000,6.5
  N,NA,DAA,NA,NA,100000,7.7
  O,MBA,EFE,10000,4,90000,9.0
  ''')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   Name    Ambition Fav_Sub  Concession  Certifications     Fee  CGPA
0     A  Placements      DL     10000.0             3.0   90000   9.5
1     B         NaN      ML     10000.0             4.0   90000   9.2
2     C      M.Tech      AI         NaN             2.0  100000   7.8
3     D         NaN      ML         NaN             NaN  100000   8.9
4     E         NaN    DBMS         NaN             NaN  100000   8.2
5     F  Placements     DAA     10000.0             4.0   90000   9.6
6     G         NaN      DS     10000.0             1.0   90000   9.0
7     H  Placements      DS     10000.0             NaN   90000   9.8
8     I         MBA      DL         NaN             2.0  100000   8.5
9     J         MBA    DBMS         NaN             NaN  100000   7.6
10    K      M.Tech      ML     10000.0             3.0   90000   9.3
11    L  Placements      AI         NaN             4.0  100000   8.7
12    M         NaN    DBMS         NaN             1.0  100000   6.5
13    N         NaN 

The Python Pandas module has a function that called get_dummies() which does one hot encoding.

For categorical input fields, we can treat NaN as a category.pandas can convert the column into two columns.

In [ ]:
inputs, targets = data.iloc[:, 0:6], data.iloc[:, 6]
inputs = pd.get_dummies(inputs, dummy_na=False)
print(inputs)


    Concession  Certifications     Fee  Name_  A  Name_  B  Name_  C  \
0      10000.0             3.0   90000         1         0         0   
1      10000.0             4.0   90000         0         1         0   
2          NaN             2.0  100000         0         0         1   
3          NaN             NaN  100000         0         0         0   
4          NaN             NaN  100000         0         0         0   
5      10000.0             4.0   90000         0         0         0   
6      10000.0             1.0   90000         0         0         0   
7      10000.0             NaN   90000         0         0         0   
8          NaN             2.0  100000         0         0         0   
9          NaN             NaN  100000         0         0         0   
10     10000.0             3.0   90000         0         0         0   
11         NaN             4.0  100000         0         0         0   
12         NaN             1.0  100000         0         0      

In [ ]:
inputs, targets = data.iloc[:, 0:6], data.iloc[:, 6]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

    Concession  Certifications     Fee  Name_  A  Name_  B  Name_  C  \
0      10000.0             3.0   90000         1         0         0   
1      10000.0             4.0   90000         0         1         0   
2          NaN             2.0  100000         0         0         1   
3          NaN             NaN  100000         0         0         0   
4          NaN             NaN  100000         0         0         0   
5      10000.0             4.0   90000         0         0         0   
6      10000.0             1.0   90000         0         0         0   
7      10000.0             NaN   90000         0         0         0   
8          NaN             2.0  100000         0         0         0   
9          NaN             NaN  100000         0         0         0   
10     10000.0             3.0   90000         0         0         0   
11         NaN             4.0  100000         0         0         0   
12         NaN             1.0  100000         0         0      

**Replacing NAN with Mean of the Values**

In [ ]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

    Concession  Certifications     Fee  Name_  A  Name_  B  Name_  C  \
0      10000.0             3.0   90000         1         0         0   
1      10000.0             4.0   90000         0         1         0   
2      10000.0             2.0  100000         0         0         1   
3      10000.0             2.8  100000         0         0         0   
4      10000.0             2.8  100000         0         0         0   
5      10000.0             4.0   90000         0         0         0   
6      10000.0             1.0   90000         0         0         0   
7      10000.0             2.8   90000         0         0         0   
8      10000.0             2.0  100000         0         0         0   
9      10000.0             2.8  100000         0         0         0   
10     10000.0             3.0   90000         0         0         0   
11     10000.0             4.0  100000         0         0         0   
12     10000.0             1.0  100000         0         0      

In [ ]:
import torch

In [ ]:
X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

(tensor([[1.0000e+04, 3.0000e+00, 9.0000e+04, 1.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+04, 4.0000e+00, 9.0000e+04, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00],
         [1.0000e+04, 2.0000e+00, 1.0000e+05, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [ ]:
A+B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [ ]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [ ]:
(a * X), (a * X).shape

(tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]), torch.Size([2, 3, 4]))

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.choice([1,np.nan], (50, 15), p=[0.3, 0.7]), columns=list('ABCDEFGHIJKLMNO'))
df

A    B    C    D    E    F    G    H    I    J    K    L    M    N    O
0   1.0  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
1   1.0  1.0  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN  NaN  1.0  NaN  1.0  NaN
2   NaN  1.0  NaN  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  1.0  NaN  1.0  NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN
5   1.0  1.0  1.0  NaN  1.0  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN
6   NaN  1.0  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN
7   NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0  NaN  1.0
8   1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0  1.0  1.0
10  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  NaN  NaN
11  1.0  NaN  NaN  1.0  1.0  NaN  1.0  NaN  1.0  1.0  NaN  1.0  1.0  1.0  NaN
12  1.0  NaN  NaN  NaN  1.0  1.0  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN  1.0
13  NaN  1.0  NaN  NaN  1.0  1.0  1.0  1.0  NaN  NaN  NaN  1.0  NaN  1.0  1.0
14  NaN  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  1.0
15  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  1.0
18  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN  1.0  1.0  NaN  1.0  NaN  NaN  1.0
19  1.0  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN
20  NaN  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  1.0  NaN  NaN
21  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  1.0
22  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  1.0  1.0
23  NaN  NaN  NaN  1.0  1.0  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0
24  NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  NaN  NaN  1.0  1.0  NaN  NaN  NaN
25  NaN  1.0  1.0  NaN  1.0  NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN  NaN
27  1.0  1.0  NaN  NaN  NaN  NaN  1.0  1.0  1.0  NaN  NaN  NaN  NaN  1.0  1.0
28  1.0  1.0  NaN  1.0  1.0  NaN  1.0  1.0  NaN  1.0  NaN  1.0  NaN  NaN  NaN
29  NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
30  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  1.0  1.0  NaN
31  NaN  NaN  1.0  NaN  1.0  NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN
33  NaN  1.0  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  1.0
34  NaN  1.0  NaN  1.0  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  1.0  NaN
35  NaN  NaN  1.0  NaN  NaN  1.0  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN
36  1.0  1.0  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0  NaN  NaN  NaN  1.0  1.0
37  NaN  NaN  1.0  NaN  1.0  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN
38  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN
39  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN
40  1.0  NaN  1.0  NaN  1.0  1.0  1.0  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN
41  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
42  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN
43  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  1.0  1.0  NaN  NaN  NaN  1.0  NaN
44  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  1.0  1.0  NaN  1.0  NaN
45  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN
46  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN
47  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  1.0  NaN  NaN
48  1.0  1.0  1.0  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN  1.0
49  NaN  1.0  1.0  1.0  NaN  1.0  1.0  NaN  NaN  1.0  NaN  1.0  NaN  1.0  NaN

In [ ]:
df.isnull().mean()

A    0.70
B    0.64
C    0.64
D    0.68
E    0.64
F    0.76
G    0.66
H    0.62
I    0.66
J    0.76
K    0.70
L    0.62
M    0.72
N    0.66
O    0.68
dtype: float64

In [ ]:
df.columns[df.isnull().mean() < 0.7]

Index(['B', 'C', 'D', 'E', 'G', 'H', 'I', 'L', 'N', 'O'], dtype='object')

In [ ]:
df[df.columns[df.isnull().mean() < 0.7]]

B    C    D    E    G    H    I    L    N    O
0   NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  1.0
1   1.0  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0  NaN
2   1.0  NaN  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
3   NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  1.0  NaN  1.0  NaN  1.0  1.0  NaN  NaN  NaN
5   1.0  1.0  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN
6   1.0  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  1.0
8   NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  1.0  1.0  NaN  NaN  NaN  1.0  NaN  1.0  1.0
10  1.0  1.0  NaN  NaN  NaN  NaN  1.0  1.0  NaN  NaN
11  NaN  NaN  1.0  1.0  1.0  NaN  1.0  1.0  1.0  NaN
12  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0  NaN  1.0
13  1.0  NaN  NaN  1.0  1.0  1.0  NaN  1.0  1.0  1.0
14  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  1.0
15  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0
18  NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  NaN  1.0
19  1.0  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN
20  NaN  NaN  1.0  NaN  1.0  NaN  NaN  1.0  NaN  NaN
21  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0
22  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  1.0  1.0
23  NaN  NaN  1.0  1.0  1.0  NaN  NaN  1.0  NaN  1.0
24  NaN  NaN  NaN  1.0  1.0  1.0  NaN  1.0  NaN  NaN
25  1.0  1.0  NaN  1.0  NaN  1.0  1.0  NaN  NaN  NaN
26  NaN  NaN  NaN  1.0  NaN  1.0  NaN  1.0  NaN  NaN
27  1.0  NaN  NaN  NaN  1.0  1.0  1.0  NaN  1.0  1.0
28  1.0  NaN  1.0  1.0  1.0  1.0  NaN  1.0  NaN  NaN
29  NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN
30  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN
31  NaN  1.0  NaN  1.0  NaN  1.0  1.0  NaN  NaN  NaN
32  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN
33  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0
34  1.0  NaN  1.0  1.0  NaN  1.0  NaN  NaN  1.0  NaN
35  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN
36  1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  1.0
37  NaN  1.0  NaN  1.0  NaN  NaN  1.0  NaN  1.0  NaN
38  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN
39  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN
40  NaN  1.0  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN
41  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
42  NaN  1.0  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN
43  1.0  NaN  1.0  NaN  NaN  NaN  1.0  NaN  1.0  NaN
44  NaN  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN
45  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
46  NaN  NaN  1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN
47  NaN  NaN  1.0  NaN  NaN  NaN  1.0  1.0  NaN  NaN
48  1.0  1.0  NaN  1.0  NaN  1.0  NaN  1.0  NaN  1.0
49  1.0  1.0  1.0  NaN  1.0  NaN  NaN  1.0  1.0  NaN

In [ ]:
import pandas as pd
import numpy as np

stud_dict = {"name": ["North", "Nox", "Gryphon", "Atlas", "Gabe"], "age": [28, 25, 26, 21, 21], "marks": [np.nan, 99.48, 91.54, np.nan, 87.34]}

# Create DataFrame from dict
stud_df = pd.DataFrame(stud_dict)
print(stud_df)

      name  age  marks
0    North   28    NaN
1      Nox   25  99.48
2  Gryphon   26  91.54
3    Atlas   21    NaN
4     Gabe   21  87.34


In [ ]:
# drop column with NaN
stud_df = stud_df.dropna(axis='columns')

print(stud_df)

      name  age
0    North   28
1      Nox   25
2  Gryphon   26
3    Atlas   21
4     Gabe   21


In [ ]:
# drop column with NaN
stud_df = stud_df.dropna(axis='rows')

print(stud_df)

      name  age
0    North   28
1      Nox   25
2  Gryphon   26
3    Atlas   21
4     Gabe   21


In [ ]:
# keep column with 3 or more non-NA values
import pandas as pd
import numpy as np

stud1_dict = {"name": ["North", "Nox", "Gryphon", "Atlas", "Gabe"], "age": [28, np.nan, 26, np.nan, np.nan], "marks": [np.nan, 99.48, 91.54, np.nan, 87.34]}

stud1_df = pd.DataFrame(stud1_dict)
print(stud1_df)
stud1_df = stud1_df.dropna(axis='columns', thresh=3)

print(stud1_df)

      name   age  marks
0    North  28.0    NaN
1      Nox   NaN  99.48
2  Gryphon  26.0  91.54
3    Atlas   NaN    NaN
4     Gabe   NaN  87.34
      name  marks
0    North    NaN
1      Nox  99.48
2  Gryphon  91.54
3    Atlas    NaN
4     Gabe  87.34


In [ ]:
# drop duplicate rows
import pandas as pd
import numpy as np

stud2_dict = {"name": ["North", "Nox", "Gabe", "Atlas", "North"], "age": [28, np.nan, 26, np.nan, 28], "marks": [np.nan, 99.48, 91.54, 87.34, np.nan]}

stud2_df = pd.DataFrame(stud2_dict)
print(stud2_df)

stud2_df = stud2_df.drop_duplicates()

print(stud2_df)

    name   age  marks
0  North  28.0    NaN
1    Nox   NaN  99.48
2   Gabe  26.0  91.54
3  Atlas   NaN  87.34
4  North  28.0    NaN
    name   age  marks
0  North  28.0    NaN
1    Nox   NaN  99.48
2   Gabe  26.0  91.54
3  Atlas   NaN  87.34


In [ ]:
import pandas as pd

df = pd.read_csv('grades.csv')

print(df)
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17    30.00     63.15  48.89
3        7       81.22     96.06    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8       96.73    103.71    45.00     93.52  61.94
95       7       85.34     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[99 rows x 6 columns]
    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96

In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60


In [ ]:
df.head()

Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17    30.00     63.15  48.89
3       7       81.22     96.06    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89

In [ ]:
df.tail()

Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
94       8       96.73    103.71    45.00     93.52  61.94
95       7       85.34     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Prefix      99 non-null     int64  
 1   Assignment  99 non-null     float64
 2   Tutorial    99 non-null     float64
 3   Midterm     99 non-null     float64
 4   TakeHome    98 non-null     float64
 5   Final       96 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 4.8 KB


In [ ]:
import pandas as pd
df = pd.read_csv('grades.csv')
new_df = df.dropna()
print(new_df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
df.dropna(inplace = True)
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

By default, the dropna() method returns a new DataFrame, and will not change the original. If you want to change the original DataFrame, use the inplace = True argument:

In [ ]:
df.fillna(111, inplace = True)
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
df["Final"].fillna(63.12, inplace = True)

print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
x = df["Final"].mean()

df["Final"].fillna(x, inplace = True)

print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
# replace the values with median and mode as well
x = df["Final"].median()
x = df["Final"].mode()[0]

In [ ]:
df.loc[8, 'Prefix'] = 8
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
for x in df.index:
  if df.loc[x, "Prefix"] < 7:
    df.loc[x, "Prefix"] = 7
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        7       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       7       86.26     80.60    74.38     87.59   77.50
12       8       97.16    103.71    72.50     93.52   63.33
13       7       91.28     83.53    81.25     99.81   92.22
14       8       84.80     89.08    44.38     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.5

In [ ]:
for x in df.index:
  if df.loc[x, "Prefix"] > 7:
    df.drop(x, inplace = True)
print(df.to_string())

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        7       57.14     34.09    64.38     51.48   52.50
3        7       81.22     96.06    49.38    105.93   80.56
5        7       95.00     92.58    93.12     97.78   68.06
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       7       86.26     80.60    74.38     87.59   77.50
13       7       91.28     83.53    81.25     99.81   92.22
15       7       93.83     95.43    88.12     80.93   90.00
17       7       92.01    102.52    38.75     86.11   49.17
23       7       80.44     90.20    46.25     91.48   72.22
24       7       53.36     82.01    74.38    102.59   56.39
25       7       91.28     95.24    82.50     97.59   92.78
29       7       91.62     65.18    71.88     90.00   45.56
30       7       98.58    102.46    67.50     97.59   63.33
31       7       86.26     88.57    70.00     87.59   55.00
33       7       98.58     91.03   101.2

SCIKIT-Simple and efficient tools for predictive data analysis Accessible to everybody, and reusable in various contexts Built on NumPy, SciPy, and matplotlib

Scikit-learn is an open source library that supports supervised and unsupervised learning. It also provides various tools for model fitting, data preprocessing, model selection, model evaluation, and many other utilities.

pip install -U scikit-learn

In [ ]:
import numpy as np
from sklearn.impute import KNNImputer
nan = np.nan
X = [[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2, weights="uniform")
imputer.fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])

In [ ]:
from sklearn.impute import SimpleImputer
#Keeping the number of features constant
imputer = SimpleImputer()
X = np.array([[np.nan, 1], [np.nan, 2], [np.nan, 3]])
imputer.fit_transform(X)

array([[1.],
       [2.],
       [3.]])

The SimpleImputer class also supports categorical data represented as string values or pandas categoricals when using the 'most_frequent' or 'constant' strategy:

In [ ]:
import pandas as pd
df = pd.DataFrame([["1", "x"],
                   [np.nan, "y"],
                   ["1", np.nan],
                   ["2", "y"]], dtype="category")
imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(df))

[['1' 'x']
 ['1' 'y']
 ['1' 'y']
 ['2' 'y']]


In [ ]:
from sklearn.datasets import load_iris
from sklearn.impute import SimpleImputer, MissingIndicator
from sklearn.model_selection import train_test_split
from sklearn.pipeline import FeatureUnion, make_pipeline
from sklearn.tree import DecisionTreeClassifier
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=50,
                                               random_state=0)

In [ ]:
X_test.shape

(50, 4)

In [ ]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2])

In [ ]:
y_train

array([1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1,
       0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0,
       2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1,
       2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2,
       0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
X_train.shape

(100, 4)