In [ ]:
#Numpy Functions
import numpy as np
a = [1,2,3,4,5]
print('array function: ')
print(np.array(a))
print()
print('asarray function: ')
b = [3,6,(7,8,9),{1,2},[4,5]]
print(np.asarray(a))
print(np.asarray(b))
print()
print('shape function: ')
print(np.shape(a))
print()
print('size function: ')
print(np.size(a))
print()
print('n-dimensional array of zeroes and ones: ')
a1 = np.zeros((3,4), dtype = np.float16)
print(a1)
print()
a2 = np.ones((3,4), dtype=np.int32)
print(a2)
print()
print('full operation: ')
a11 = np.full((3,3),5,dtype=np.int64)
print(a11)
print()
print('Getting an array of evenly spaced values with np.arange and np.linspace: ')
print(np.linspace(1,10,num=5,endpoint=True,retstep=True))
print()
print(np.arange(start=1,stop=10,step=2))

array function: 
[1 2 3 4 5]

asarray function: 
[1 2 3 4 5]
[3 6 (7, 8, 9) {1, 2} list([4, 5])]

shape function: 
(5,)

size function: 
5

n-dimensional array of zeroes and ones: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

full operation: 
[[5 5 5]
 [5 5 5]
 [5 5 5]]

Getting an array of evenly spaced values with np.arrange and np.linspace: 
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

[1 3 5 7 9]


<ipython-input-8-f31ee980c71f>:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.asarray(b))


In [ ]:
#Tensorflow Functions
import tensorflow as tf
print(tf.math.add(5,6))
print(tf.math.multiply(2,3))
print(tf.math.square(tf.math.add([1,2,3],[4,5,6])))
print(tf.math.reduce_sum([1,2,3]))
print()
print('Matrix Multiplication: ')
x = tf.linalg.matmul([[1, 2]], [[1,2],[1,2]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([25 49 81], shape=(3,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)

Matrix Multiplication: 
tf.Tensor([[3 6]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
#turning strings into sequences of integer word indices
from tensorflow.keras.layers import TextVectorization
training_data = np.array([["This is the school that calls itself a college"], ["The school is VCE, assumed to be the best college"]])
print(training_data)
vectorizer = TextVectorization(output_mode="int")
vectorizer.adapt(training_data)
integer_data = vectorizer(training_data)
print(integer_data)

[['This is the school that calls itself a college']
 ['The school is VCE, assumed to be the best college']]
tf.Tensor(
[[ 8  4  2  3  9 11 10 15  5  0]
 [ 2  3  4  6 14  7 13  2 12  5]], shape=(2, 10), dtype=int64)


In [ ]:
from tensorflow.keras.layers import CenterCrop
from tensorflow.keras.layers import Rescaling

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

cropper = CenterCrop(height=100, width=100)
scaler = Rescaling(scale=1.0 / 255)

output_data = scaler(cropper(training_data))
print("shape:", output_data.shape)
print("min:", np.min(output_data))
print("max:", np.max(output_data))

shape: (64, 100, 100, 3)
min: 0.0
max: 1.0


In [ ]:
#PyTorch Operations
import torch
x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values
z1 = x + y
print(z1)
print(torch.add(x, y))
print()
x1 = torch.rand(2, 3)
y1 = torch.rand(2, 3)    # Initialize with random values
# Operations
z2 = x1 + y1
print(z2)
print(torch.add(x, y))
print()
#Conversion from NumPy array to Tensor
a = np.array([1, 2, 3])
print(torch.from_numpy(a))
print()
print(torch.randperm(4))
print()
print(torch.ones(10))
print()
print(torch.ones(2,1))
print()
print(torch.zeros(10))
print()
eyes = torch.eye(3)
print(torch.ones_like(eyes))

tensor([[0.2506, 0.7714, 0.6308],
        [0.2307, 0.1194, 0.3276]])
tensor([[0.2506, 0.7714, 0.6308],
        [0.2307, 0.1194, 0.3276]])

tensor([[0.6841, 1.1355, 1.4719],
        [0.4686, 0.7837, 1.0870]])
tensor([[0.2506, 0.7714, 0.6308],
        [0.2307, 0.1194, 0.3276]])

tensor([1, 2, 3])

tensor([2, 3, 1, 0])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

tensor([[1.],
        [1.]])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
